### ISSUE TITLE
Invalid thing description from sample multiple thing

### ISSUE THREAD

**Issue by brvier** [mozilla-iot/webthing-python#11]
While trying sample multiple_thing i got a "Invalid thing description" when adding things in gateway.

And it s working if i remove 'sensor' or 'light' from line 152
`server = WebServer([....`

**Comment by mrstegeman** [comment]
When you remove one of the Things, the server serves up a single thing description at `/`. With multiple, it serves up an array (instead of an object).

Presently, you can't add a server that serves multiple things through the UI, but if `thing-url-adapter` finds it via mDNS, all of the things will be detected properly, and should just be displayed automatically on the Add Things screen.

**Comment by brvier** [comment]
Indeed, it didnt detect it via mDNS, so i enter manually url.

Thanks

**Comment by brvier** [comment]
Finally an other simple solution is to add it manually with the index of the array

Ie
http://192.168.100.112:8882/0
http://192.168.100.112:8882/1
