### ISSUE TITLE
About using raspiberry  to create Camera or VideoCamera

### ISSUE THREAD

**Issue by liu-yuanpeng** [mozilla-iot/webthing-python#45]
How should I set it up?
for example  add_property

**Comment by mrstegeman** [comment]
You can use the following as a Camera example: https://github.com/mrstegeman/photo-cycler-webthing/tree/master/python

It isn't explicitly a Camera, but it does have an ImageProperty. If you just add Camera to the types array when you initialize the Thing object, it will then be a Camera.

I have not yet tried a VideoCamera. Right now, the gateway only supports video streams via the [ONVIF adapter](https://github.com/mozilla-iot/onvif-adapter). What it does is [transcode the RTSP stream](https://github.com/mozilla-iot/onvif-adapter/blob/master/lib/onvif-device.js#L237-L324) to MPEG-DASH and/or HLS, so that it can be streamed by the browser. Ideally, a native web thing would just present a stream in one of those formats, so it would be included in the [links array](https://github.com/mrstegeman/photo-cycler-webthing/blob/master/python/photo-cycler-webthing.py#L45-L51) of the VideoProperty (see [this](https://github.com/mozilla-iot/onvif-adapter/blob/master/lib/onvif-device.js#L95-L109)), just like with the ImageProperty. In theory, that should be all you need, although I suspect we'll end up with some proxying issues. It'd be great to give it a shot, though, so that we can work through those issues.

**Comment by liu-yuanpeng** [comment]
Thank you very much. I will try to build webthings. Thanks
